apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b-deployment
  labels:
    app: internal-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: internal-api
  template:
    metadata:
      labels:
        app: internal-api
    spec:
      containers:
      - name: internal-api
        image: naftali96/coordinates_internal_api:v5
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_HOST
          value: "redis-0.redis-headless"
        - name: REDIS_PORT
          value: "6379"
