apiVersion: v1
kind: Service
metadata:
  name: external-api-service
spec:
  type: NodePort
  selector:
    app: external-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30010